---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Update apt Cache
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Wait for APT Lock
      shell:  while fuser /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock /var/cache/debconf/config.dat.lockfront /var/cache/debconf/passwords.dat.lockfront /var/lib/dpkg/lock-frontend; do sleep 10; done;

    - name: Install Python pip package manager
      become: true
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install Flask using pip
      pip:
        name: flask
        state: present

    - name: Install gunicorn using pip
      pip:
        name: gunicorn
        state: present

    - name: Install mysql-connector-python
      pip:
        name: mysql-connector-python
        state: present
    
    - name: Copy folder from local host to remote destination
      copy:
        src: app/
        dest: /root/app/
    
    - name: App DB config
      template:
        src: "app/app.py.j2"
        dest: "/root/app/app.py"

    - name: Change permission of flask_script
      command: chmod +x create_flask_service.sh
      args:
        chdir: /root/app

    - name: Execute flask script
      command: ./create_flask_service.sh
      args:
        chdir: /root/app

